# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

  strategy:
    parallel: 5
  workspace:
    clean: all
  steps:
    - checkout: none
    - task: DownloadBuildArtifacts@0
      inputs:
        buildType: 'current'
        downloadType: 'single'
        artifactName: 'testdrop'
        itemPattern: '**'
        downloadPath: '$(Build.BinariesDirectory)'
    - task: VSTest@2
      inputs:
        testSelector: 'testAssemblies'
        testAssemblyVer2: 'My.*Test.dll'
        searchFolder: '$(Build.BinariesDirectory)\testdrop'
        testFiltercriteria: 'TestCategory!=Dummy'
        runInParallel: true
        codeCoverageEnabled: false
        distributionBatchType: 'basedOnExecutionTime'
        batchingBasedOnExecutionTimeOption: 'customTimeBatchSize'
        customRunTimePerBatchValue: '480'
        rerunFailedTests: true
        rerunMaxAttempts: '5'
